export const PAGE_NAME_ROOT = {
  HOME: 'HOME',
  TAB_RESTAURANT: 'TAB_RESTAURANT',
} as const;

export const TAB_NAME = {
  RANDOM_RESTAURANT: 'RANDOM_RESTAURANT',
  RESTAURANT_WITH_PRIVATE_ROOM: 'RESTAURANT_WITH_PRIVATE_ROOM',
} as const;
